routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('contactform');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/', 'MessagesController@store');
Route::post('send-email', 'MessagesController@store')->name('email');

Route::get('/pruebas', function () {

    return view('prueba-faqs');

});

Route::get('/admin','HomeController@admin')->name('admin');
Route::resource('bolson','BolsonController');

Auth::routes();

app/Bolson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bolson extends Model
{
    public $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BolsonController.php
<?php

namespace App\Http\Controllers;

use App\Bolson;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BolsonController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bolson = Bolson::all()->last();
        $vac = compact('bolson');
        return view('admin.bolson.create',$vac);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Storage::delete('imagen-bolson-mes.jpg');
        Storage::disk('public')->delete('images/mobile/imagen-bolson-mes.png');
        Storage::disk('public')->delete('images/tablet/imagen-bolson-mes.png');
        Storage::disk('public')->delete('images/desktop/imagen-bolson-mes.png');

        $fileMobile = $request['mobile'];
        $nameMobile = 'imagen-bolson-mes' . "." . $fileMobile->extension();
        $pathMobile = $fileMobile->storeAs('images/mobile', $nameMobile, 'public');

        $fileTablet = $request['tablet'];
        $nameTablet = 'imagen-bolson-mes' . "." . $fileTablet->extension();
        $pathTablet = $fileTablet->storeAs('images/tablet', $nameTablet, 'public');

        $fileDesktop = $request['desktop'];
        $nameDesktop = 'imagen-bolson-mes' . "." . $fileDesktop->extension();
        $pathDesktop = $fileDesktop->storeAs('images/desktop', $nameDesktop, 'public');

        $bolson = Bolson::create([
            'image_mobile'  => $pathMobile,
            'image_tablet'  => $pathTablet,
            'image_desktop' => $pathDesktop
        ]);
        $vac = compact('bolson');
        return view('admin.index',$vac);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function admin()
    {
        return view('admin.index');
    }
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use App\Mail\MessageReceived;
use Illuminate\Support\Facades\Mail;

class MessagesController extends Controller
{
    public function store() {

        $msg = request();
        
        Mail::to('consumidores@elclickbolsones.com')->send(new MessageReceived($msg));

        $mensaje = "Mensaje Enviado";
        return $mensaje;
    }
}

resources/views/admin/bolson/create.blade.php
@extends('layouts.admin')
@section('content')
    <form action="{{ route('bolson.store') }}" method="post" enctype="multipart/form-data" class="formadmin">
        @csrf
        @method('post')
        <div class="row">
            <div class="form-group col-4 col-lg-3 mx-auto text-center">    
                <label class="h3" for="">Imagen Mobile</label>
                <input name="mobile" type="file" class="form-control-file">
            </div>
            <div class="form-group col-4 col-lg-3 mx-auto text-center">    
                <label class="h3" for="">Imagen Tablet</label>
                <input name="tablet" type="file" class="form-control-file">
            </div>
            <div class="form-group col-4 col-lg-3 mx-auto text-center">    
                <label class="h3" for="">Imagen Desktop</label>
                <input name="desktop" type="file" class="form-control-file">
            </div>
        </div>
        <div class="col-6 mx-auto text-center">
            <button class="btn btn-success" type="submit">S u b i r</button>
        </div>
    </form>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="col-6 mx-auto text-center divcambiar fuenteadmin">
        <a href="{{ route('bolson.create') }}"><button class="btn btn-info">Cambiar imagen</button></a>
    </div>
    @if (isset($bolson))
    <div class="row mt-5 fuenteadmin">
        <div class="col-12 text-center">
            <h2>Ultimo bolson</h2>
        </div>
        <div class="col-4 col-lg-3 mx-auto text-center">
            <h3>Imagen Mobile</h3>
            <img class="w-100" src="{{ asset('storage/'.$bolson->image_mobile) }}" alt="ultimo bolson">
        </div>
        <div class="col-4 col-lg-3 mx-auto text-center">
            <h3>Imagen Tablet</h3>
            <img class="w-100" src="{{ asset('storage/'.$bolson->image_tablet) }}" alt="ultimo bolson">
        </div>
        <div class="col-4 col-lg-3 mx-auto text-center">
            <h3>Imagen Desktop</h3>
            <img class="w-100" src="{{ asset('storage/'.$bolson->image_desktop) }}" alt="ultimo bolson">
        </div>
    </div>
    @endif
@endsection

resources/views/carrousel.blade.php
@extends('googleform')
@section('carrousel')
<h2 class="text-center titulocarrusel">¿POR QUÉ HACEMOS EL CLICK?</h2>
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators carruselindicadores">
    <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-2" data-slide-to="1"></li>
    <li data-target="#carousel-example-2" data-slide-to="2"></li>
    <li data-target="#carousel-example-2" data-slide-to="3"></li>

  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="view">
        <img class="imgcarruselmobile w-100" src="{{ asset('storage/images/Mobile-ImagenesSlide/El-Click-Web-Mobile-ImagenesSlide-01.jpg') }}">
        <img class="imgcarruseltablet w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-01.jpg') }}">
        <img class="imgcarruseldesk w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-01.jpg') }}">
        <div class="mask rgba-black-light"></div>
      </div>
      <div class="carousel-caption">
        <h1 class="h3-responsive h3carrusel margenh3carr">COMEMOS MÁS</h1>
        <h1 class="h3-responsive h3carrusel margenh3carr">SANO Y RICO</h1>
        <hr class="bordecarrusel"></hr>
        <p class="parrafocarrusel text-center"> Las frutas y verduras libres de agrotóxicos tienen doble beneficio: mantienen todos sus nutrientes y su sabor real. ¡Trabajamos con alimentos recién cosechados! </p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="view">
        <img class="imgcarruselmobile w-100" src="{{ asset('storage/images/Mobile-ImagenesSlide/El-Click-Web-Mobile-ImagenesSlide-02.jpg') }}">
        <img class="imgcarruseltablet w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-02.jpg') }}">
        <img class="imgcarruseldesk w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-02.jpg') }}">
        <div class="mask rgba-black-strong"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive h3carrusel 2-line mb-0">MEJORAMOS EL TRABAJO</h3>
        <h3 class="h3-responsive h3carrusel 2-line">DE PEQUEÑXS PRODUCTORXS</h3>
        <hr class="bordecarrusel"></hr>
        <p class="parrafocarrusel text-center"> La agroecología y el sistema de bolsones son una oportunidad real de trabajo digno y sano para más personas. ¡El 60% del valor del bolsón va directo a las familias productoras! </p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="view">
        <img class="imgcarruselmobile w-100" src="{{ asset('storage/images/Mobile-ImagenesSlide/El-Click-Web-Mobile-ImagenesSlide-03.jpg') }}">
        <img class="imgcarruseltablet w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-03.jpg') }}">
        <img class="imgcarruseldesk w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-03.jpg') }}">
        <div class="mask rgba-black-slight"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive h3carrusel margenh3carr">CAMBIAMOS HÁBITOS</h3>
        <h3 class="h3-responsive h3carrusel margenh3carr">DESDE EL CONSUMO</h3>
        <hr class="bordecarrusel"></hr>
        <p class="parrafocarrusel text-center"> Buscamos ser una alternativa al mercado convencional de producción y desde un compromiso colectivo podemos lograr acceder a alimentos más sanos y a un mejor precio. </p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="view">
        <img class="imgcarruselmobile w-100" src="{{ asset('storage/images/Mobile-ImagenesSlide/El-Click-Web-Mobile-ImagenesSlide-04.jpg') }}">
        <img class="imgcarruseltablet w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-04.jpg') }}">
        <img class="imgcarruseldesk w-100" src="{{ asset('storage/images/Desktop-ImagenesSlide/El-Click-Web-Desktop-ImagenesSlide-04.jpg') }}">
        <div class="mask rgba-black-slight"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive h3carrusel 2line margenh3carr"> INCENTIVAMOS EL </h3>
        <h3 class="h3-responsive h3carrusel 2line margenh3carr"> RESPETO POR LA TIERRA</h3>
        <hr class="bordecarrusel"></hr>
        <p class="parrafocarrusel text-center"> En momentos de emergencia climática creemos que la agroecología es el camino. Una forma de cultivar que convive con el ecosistema en vez de destruirlo. </p>
      </div>
    </div>
  </div>

</div>

<div class="carruselseparador">
</div>



    @yield('contact')
@endsection

resources/views/contactform.blade.php
@extends('carrousel')
@section('contact')

    <div class="container-fluid">
        <div class="row contact-form">
            <div class="col-md-12 col-lg-6">
                <p id="dform"></p>
                <div class="title text-center mx-auto">
                    <h2>CONTACTO</h2>
                </div>
                <div class="sub-title text-center mx-auto">
                    <p>Escribinos y te responderemos a la brevedad</p>
                <img src="{{ asset('storage/images/Iconos/Icono-08.svg') }}" alt="">
                </div>
                <div class="formulario">
                <form id="contactForm" action="{{ route('email') }}" method="POST">
                    @csrf
                        <div class="form-group row">
                        <div class="col-sm-6 col-md-8 col-lg-10 mx-auto">
                            <input type="text" name="nombre" class="form-control rounded-pill" id="inputText" placeholder="Nombre" required>
                        </div>
                        </div>
                        <div class="form-group row">
                        <div class="col-sm-6 col-md-8 col-lg-10 mx-auto">
                            <input type="email" name="email" class="form-control rounded-pill" id="inputEmail" placeholder="Mail" required>
                        </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 col-md-8 col-lg-10 mx-auto">
                                <textarea class="form-control" name="mensaje" id="FormControlTextarea" rows="10" placeholder="Mensaje"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                        <div class="mx-auto">
                            <button type="submit" id="btnEnviar" class="btn btn-success rounded-pill" onclick="sendEmail()">Enviar</button>
                        </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="img-form col-6"></div>
        </div>    
    </div>
@endsection

resources/views/content.blade.php
@extends('layouts.app')
@section('content')
    <section class="contenido" id="bolson">
        <img alt="banner-primera-seccion" id="banner" class="banner">
        <div class="boton">
            <a href="#gform"><button type="button" class="bc1 btn btn-success" id="boton">PEDÍLO ACÁ</button></a>
        </div>    
       <div class="ancla"><p id="faqs"></p></div>
    </section>
    @yield('faqs')
@endsection

resources/views/googleform.blade.php
@extends('faqs')
@section('google')
    <div id="gform" class="google-form">
        <div class="title-form text-center mx-auto">
            <h2>COMPLETÁ EL FORMULARIO Y TU PEDIDO QUEDARÁ CONFIRMADO</h2>
        </div>
        <div class="formulario justify-content-center">
            <iframe id="google-form" class="w-100" src="https://docs.google.com/forms/d/e/1FAIpQLScJbsGNlCqwNAi2H2EvgDcYdUiOkimnMiNqFr8RmCLBAEzJew/viewform?embedded=true">Cargando…</iframe>
        </div>
    </div>
    @yield('carrousel')    
@stop
@section('scripts')
@stop

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>El Click</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Iconos -->
    <script src="https://kit.fontawesome.com/4baeadfaf1.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;900&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    
</head>
<body>
    <div id="admin">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
            <a class="navbar-brand" href="#">
                <img src="{{ asset('storage/images/mobile/El Click-Web-Mobile_LOGO.svg') }}" width="80" height="70" alt="logo el click">
            </a>
            <div class="text-center">
                <h4 class="navbar-text">
                    FRUTAS Y VERDURAS LIBRES DE AGROTÓXICOS
                </h4>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav justify-content-end mt-2 mt-lg-0">
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">Registrarse</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                Bienvenido {{ ucfirst(Auth::user()->name) }} <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    {{ __('Cerrar sesión') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </nav>
    </div>
    <main style="padding-top: 10%">
        @yield('content')
    </main>
    @yield('scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>El Click</title>
    <!-- Pop-up JS -->
    <script src="/js/pop-up.js" defer></script>
    
    <!-- Section JS -->
    <script src="/js/section.js" defer></script>

    <!-- Bootstrap CSS -->
    {{-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> --}}
    <!-- Iconos -->
    <script src="https://kit.fontawesome.com/4baeadfaf1.js" crossorigin="anonymous"></script>

    {{-- <script src="https://unpkg.com/scrollreveal"></script> --}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    {{-- <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;900&display=swap" rel="stylesheet"> --}}

    <!-- Styles -->
    <link href="{{ asset('/css/app.css') }}" rel="stylesheet"> 
    <!-- Styles -->
    <link href="{{ asset('/css/pop-up.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/section.css') }}" rel="stylesheet"> 

</head>
<body>
  <div class="pop-up__container" id="pop-up__container"></div>
  <div class="preloader-wrapper">
    <div class="preloader"></div>
  </div>

      

    <div id="app">
      <a href="https://api.whatsapp.com/send?phone=5491136718145&text=" target="_blank" class="float">
       <i class="fab fa-whatsapp my-float"></i>
      </a>
      <div class="label-container">
       <div class="label-text">Hola! Consultános lo que precises y te responderemos a la brevedad.</div>
       <i class="fa fa-play label-arrow"></i>
      </div>
        {{-- Barra de navegacion --}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow headline">
            <a class="navbar-brand" href="#">
                <img src="{{ asset('/images/mobile/El Click-Web-Mobile_LOGO.svg') }}" width="80" height="70" alt="logo el click">
            </a>
            <div class="text-center titulonav">
                <h4 class="navbar-text">
                  <div class="tagline h4barranav">FRUTAS Y VERDURAS LIBRES DE AGROTÓXICOS</div>
                </h4>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
              <ul class="navbar-nav text-center justify-content-end mt-2 mt-lg-0">
                <li class="nav-item">
                  <a class="nav-link" href="#bolson">El bolsón</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#faqs">Info importante</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#gform">Pedílo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#dform">Contacto</a>
                  </li>
              </ul>
            </div>
        </nav>
        <main>
            @yield('content')
        </main>
        <footer>
            <div class="part-footer f-l">
                <h3>¡SEGUINOS!</h3>
            </div>
            <div class="part-footer f-m">
                <div class="social-media">
                    <a href="https://www.instagram.com/elclickbolsones/"><i class="fab fa-instagram"></i></a>
                    <a href="https://www.facebook.com/elclickbolsones/"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-whatsapp"></i></a>
                </div>
            </div>
        </footer>
    </div>

    @stack('scripts')
    <!-- Scripts -->
    <script src="{{ mix('/js/app.js') }}"></script>
    
</body>
</html>